version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    networks:
      - microservices_network
    volumes:
      - ./auth_service:/app

  carbon_tracking_service:
    build:
      context: ./carbon_tracking_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    networks:
      - microservices_network
    volumes:
      - ./carbon_tracking_service:/app

  game_service:
    build:
      context: ./game_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    networks:
      - microservices_network
    volumes:
      - ./game_service:/app

networks:
  microservices_network:
    driver: bridge
