version: '3.8'

services:
  core_service:
    build: 
      context: ./core_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - AUTH_SERVICE_URL=http://localhost:8001
      - CARBON_SERVICE_URL=http://localhost:8002
      - GAME_SERVICE_URL=http://localhost:8003
    depends_on:
      - auth_service
      - carbon_tracking_service
      - game_service
    networks:
      - microservices_network

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    networks:
      - microservices_network

  carbon_tracking_service:
    build:
      context: ./carbon_tracking_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./.env
    networks:
      - microservices_network

  game_service:
    build:
      context: ./game_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge