version: '3.8'

services:
  core_service:
    build:
      context: ./core_service
      dockerfile: Dockerfile
    container_name: core_service
    ports:
      - "8000:8000"
    env_file:
      - ./core_service/.env
    depends_on:
      - auth_service
      - carbon_tracking_service

  carbon_tracking_service:
    build:
      context: ./carbon_tracking_service
      dockerfile: Dockerfile
    container_name: carbon_tracking_service
    ports:
      - "8002:8002"
    env_file:
      - ./carbon_tracking_service/.env
    depends_on:
      - auth_service

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8001:8001"
    env_file:
      - ./auth_service/.env
