// pages/FAQ.jsx
import React from 'react';
import Card from '../components/Card';

const FAQ = () => {
 const faqs = [
   {
     question: "What is a carbon footprint? 🌍",
     answer: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It includes the emissions from your home energy use, transportation, diet, and consumer habits."
   },
   {
     question: "How is my carbon footprint calculated? 📊",
     answer: "We calculate your carbon footprint based on several factors including your home energy consumption, transportation methods, and daily habits. Our algorithm uses standardized emission factors from reputable environmental databases."
   },
   {
     question: "How can I reduce my carbon footprint? 💚",
     answer: "There are many ways to reduce your carbon footprint: use energy-efficient appliances, opt for public transportation or walking, reduce meat consumption, recycle, and choose renewable energy sources when possible."
   },
   {
     question: "How often should I track my carbon footprint? 📅",
     answer: "We recommend tracking your carbon footprint monthly to maintain accurate records and see your progress over time. Regular tracking helps you identify areas where you can make improvements."
   },
   {
     question: "Are the recommendations personalized? 🎯",
     answer: "Yes! Our recommendations are tailored based on your specific carbon footprint data and lifestyle patterns. We analyze your inputs to suggest the most effective ways for you to reduce your environmental impact."
   }
 ];

 return (
   <div className="min-h-screen bg-green-50 py-8">
     <div className="max-w-4xl mx-auto px-6">
       <h1 className="text-3xl font-semibold text-green-800 mb-8">Frequently Asked Questions</h1>
       
       <div className="space-y-6">
         {faqs.map((faq, index) => (
           <Card key={index} variant="bordered" className="p-8">
             <h3 className="text-xl font-semibold text-green-800 mb-4">{faq.question}</h3>
             <p className="text-green-700 leading-relaxed">{faq.answer}</p>
           </Card>
         ))}
       </div>

       <Card variant="bordered" className="mt-8 p-8 text-center">
         <h2 className="text-xl font-semibold text-green-800 mb-4">Still have questions? 💭</h2>
         <p className="text-green-700 mb-6">We're here to help! Contact our support team or check out our detailed guides.</p>
         <div className="flex justify-center space-x-4">
           <a 
             href="mailto:support@ecotrack.com" 
             className="px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
           >
             Contact Support
           </a>
           <a 
             href="/guides" 
             className="px-6 py-3 border border-green-600 text-green-600 rounded-lg hover:bg-green-50 transition-colors"
           >
             View Guides
           </a>
         </div>
       </Card>
     </div>
   </div>
 );
};

export default FAQ;